package com.RoieIvri.CouponsPhase2.COMPANY;

public enum CompanyExceptionTypes {
    COMPANY_NOT_FOUND_BY_ID,
    CANNOT_ADD_NULL_COUPON,
    CANNOT_ADD_NULL_COMPANY,
    COMPANY_IS_NULL,
    COUPON_ALREADY_EXIST,
    COMPANY_DONT_HAVE_THAT_COUPON
}
